Entreprise/Models/Vendor.cs
using System.ComponentModel.DataAnnotations;

namespace Entreprise.Models
{
    public class Vendor
    {
        [Key]
        public int Id { get; set; }

        public string? Name { get; set; }
        public string? Email { get; set; }
        public int Phone_Number { get; set; }
        public virtual ICollection<Product>? Products { get; set; }
    }
}

Entreprise/Controllers/StockController.cs
using Entreprise.Data;
using Entreprise.Models;
using Microsoft.AspNetCore.Mvc;

namespace Entreprise.Controllers
{
    public class StockController : Controller
    {
        private Unit UnitOfWork;
        public StockController()
        {
            this.UnitOfWork = new Unit();
        }
        public IActionResult Index()
        {
            if (HttpContext.Session.GetString("Status") == "logged")
            {
                ViewData["logged"] = "true";
                return View((ICollection<Stock>)this.UnitOfWork.Stock.GetAll());

            }
            return Redirect("/login");
            
        } 
      

        public IActionResult AllProduct(int id)
        {
            if (HttpContext.Session.GetString("Status") == "logged")
            {
                ViewData["role"] = this.UnitOfWork.User.getByID(Convert.ToInt32(HttpContext.Session.GetString("pid"))).ROLE;

                ViewData["logged"] = "true";
                return View(this.UnitOfWork.Product.GetbyStock(this.UnitOfWork.Stock.GetById(id)));
              //  return View(this.UnitOfWork.Stock.GetById(id).Products);
            }
            return Redirect("/login");
        }

        

        [HttpGet]
        public IActionResult CreateProduct()
        {
            if (HttpContext.Session.GetString("Status") == "logged" && HttpContext.Session.GetString("role") == "CEO")
            {
                
                ViewBag.Vendor = this.UnitOfWork.Vendor.GetAll();
                ViewBag.Stock = this.UnitOfWork.Stock.GetAll();
                ViewBag.Category = this.UnitOfWork.Category.GetAll();
                ViewData["logged"] = "true";
                return View();

            }
            return Redirect("/login");
        }

        [HttpPost]
        public IActionResult CreateProduct(MyViewModelProduct p)
        {
            if (HttpContext.Session.GetString("Status") == "logged" && HttpContext.Session.GetString("role") == "CEO")
            {
                p.product.Vendor = this.UnitOfWork.Vendor.GetById(p.vendor);
                p.product.Category = this.UnitOfWork.Category.GetById(p.category);
                p.product.Stock = this.UnitOfWork.Stock.GetById(p.stock);
                this.UnitOfWork.Product.Add(p.product);
                this.UnitOfWork.Vendor.GetById(p.vendor).Products.Add(p.product);
                this.UnitOfWork.Stock.GetById(p.stock).Products.Add(p.product);
                this.UnitOfWork.Category.GetById(p.category).Products.Add(p.product);
                this.UnitOfWork.complete();
                return RedirectToAction("AllProduct", new {id = p.stock });

            }
            return Redirect("/login");
        }


        [HttpGet]
        public IActionResult EditProduct(int id)
        {
            if (HttpContext.Session.GetString("Status") == "logged" && HttpContext.Session.GetString("role") == "CEO")
            {

                ViewBag.Vendor = this.UnitOfWork.Vendor.GetAll();
                ViewBag.Stock = this.UnitOfWork.Stock.GetAll();
                ViewBag.Category = this.UnitOfWork.Category.GetAll();
                ViewData["logged"] = "true";
                MyViewModelProduct p= new MyViewModelProduct();
                p.product = this.UnitOfWork.Product.GetById(id);
                p.vendor = this.UnitOfWork.Product.GetById(id).Vendor.Id;
                p.category=this.UnitOfWork.Product.GetById(id).Category.Id;
                p.stock = this.UnitOfWork.Product.GetById(id).Stock.Id;
                return View(p);

            }
            return Redirect("/login");
        }

        [HttpPost]
        public IActionResult EditProduct(MyViewModelProduct p)
        {
            if (HttpContext.Session.GetString("Status") == "logged" && HttpContext.Session.GetString("role") == "CEO")
            {
                p.product.Vendor.Products.Remove(p.product);
                this.UnitOfWork.Vendor.GetById(p.vendor).Products.Add(p.product);
                p.product.Vendor = this.UnitOfWork.Vendor.GetById(p.vendor);
                
                p.product.Category.Products.Remove(p.product);
                this.UnitOfWork.Category.GetById(p.category).Products.Add(p.product);
                p.product.Category = this.UnitOfWork.Category.GetById(p.category);
                
                p.product.Stock.Products.Remove(p.product);
                this.UnitOfWork.Stock.GetById(p.stock).Products.Add(p.product);
                p.product.Stock = this.UnitOfWork.Stock.GetById(p.stock);
                
                this.UnitOfWork.Product.UpdateProduct(p.product);
                this.UnitOfWork.complete();
                return RedirectToAction("AllProduct", new { id = p.stock });

            }
            return Redirect("/login");
        }

        public IActionResult Details(int id)
        {
            if (HttpContext.Session.GetString("Status") == "logged")
            {
                ViewData["role"] = this.UnitOfWork.User.getByID(Convert.ToInt32(HttpContext.Session.GetString("pid"))).ROLE;

                ViewData["logged"] = "true";
                return View(this.UnitOfWork.Product.GetById(id));

            }
            return Redirect("/login");
        }

        public IActionResult Delete(int id)
        {
            if (HttpContext.Session.GetString("Status") == "logged" && HttpContext.Session.GetString("role") == "CEO")
            {
                int idstock = this.UnitOfWork.Product.GetById(id).Stock.Id;
                this.UnitOfWork.Product.Remove((Product)this.UnitOfWork.Product.GetById(id));

                ViewData["logged"] = "true";
                this.UnitOfWork.complete();
                return RedirectToAction("AllProduct", new { id = idstock });
            }
                return Redirect("/login");

        }
        
        public IActionResult Category()
        {
            if (HttpContext.Session.GetString("Status") == "logged")
            {
                ViewData["role"] = this.UnitOfWork.User.getByID(Convert.ToInt32(HttpContext.Session.GetString("pid"))).ROLE;
                ViewData["logged"] = "true";
                return View(this.UnitOfWork.Category.GetAll());

            }
            return Redirect("/login");
        }
        public IActionResult CategoryProducts(int id)
        {
            if (HttpContext.Session.GetString("Status") == "logged")
            {
                ViewData["role"] = this.UnitOfWork.User.getByID(Convert.ToInt32(HttpContext.Session.GetString("pid"))).ROLE;
                ViewData["logged"] = "true";
                return View(this.UnitOfWork.Product.GetbyCategory(this.UnitOfWork.Category.GetById(id)));
                //return View(this.UnitOfWork.Category.GetById(id).Products);

            }
            return Redirect("/login");
        }
        [HttpGet]
        public IActionResult AddCategory()
        {
            if (HttpContext.Session.GetString("Status") == "logged" && HttpContext.Session.GetString("role") == "CEO")
            {

                ViewData["logged"] = "true";
                this.UnitOfWork.complete();
                return View();
            }
            return Redirect("/login");
        }
        [HttpPost]
        public IActionResult AddCategory(Category c)
        {
            if (HttpContext.Session.GetString("Status") == "logged" && HttpContext.Session.GetString("role") == "CEO")
            {
                this.UnitOfWork.Category.Add(c);
                ViewData["logged"] = "true";
                this.UnitOfWork.complete();
                return RedirectToAction("Category");
            }
            return Redirect("/login");
        }

        public IActionResult DeleteCategory(int id)
        {
            if (HttpContext.Session.GetString("Status") == "logged" && HttpContext.Session.GetString("role") == "CEO")
            {

                this.UnitOfWork.Category.Remove((Category)this.UnitOfWork.Category.GetById(id));
                ViewData["logged"] = "true";
                this.UnitOfWork.complete();
                return RedirectToAction("Category");
            }
            return Redirect("/login");

        }
        [HttpGet]
        public IActionResult EditCategory(int id)
        {
            if (HttpContext.Session.GetString("Status") == "logged" && HttpContext.Session.GetString("role") == "CEO")
            {

                ViewData["logged"] = "true";

                return View(this.UnitOfWork.Category.GetById(id));

            }
            return Redirect("/login");
        }

        [HttpPost]
        public IActionResult EditCategory(Category c)
        {
            if (HttpContext.Session.GetString("Status") == "logged" && HttpContext.Session.GetString("role") == "CEO")
            {
                this.UnitOfWork.Category.UpdateCategory(c);
                this.UnitOfWork.complete();
                return RedirectToAction("Category");

            }
            return Redirect("/login");
        }
    }
}

Entreprise/Controllers/VendorController.cs
using Entreprise.Data;
using Entreprise.Models;
using Microsoft.AspNetCore.Mvc;

namespace Entreprise.Controllers
{
    public class VendorController : Controller
    {
        private Unit UnitOfWork;
        public VendorController()
        {
            this.UnitOfWork = new Unit();
        }
        public IActionResult Index()
        {
            if (HttpContext.Session.GetString("Status") == "logged")
            {
                ViewData["role"] = this.UnitOfWork.User.getByID(Convert.ToInt32(HttpContext.Session.GetString("pid"))).ROLE;
                ViewData["logged"] = "true";
                return View(this.UnitOfWork.Vendor.GetAll());

            }
            return Redirect("/login");
        }
        public IActionResult VendorProducts(int id)
        {
            if (HttpContext.Session.GetString("Status") == "logged")
            {
                ViewData["role"] = this.UnitOfWork.User.getByID(Convert.ToInt32(HttpContext.Session.GetString("pid"))).ROLE;
                ViewData["logged"] = "true";
                return View(this.UnitOfWork.Product.GetbyVendor(this.UnitOfWork.Vendor.GetById(id)));
                //return View(this.UnitOfWork.Vendor.GetById(id).Products);
            }
            return Redirect("/login");
        }

        public IActionResult DeleteVendor(int id)
        {
            if (HttpContext.Session.GetString("Status") == "logged" && HttpContext.Session.GetString("role") == "CEO")
            {

                this.UnitOfWork.Vendor.Remove((Vendor)this.UnitOfWork.Vendor.GetById(id));
                ViewData["logged"] = "true";
                this.UnitOfWork.complete();
                return RedirectToAction("Index");
            }
            return Redirect("/login");

        }
        [HttpGet]
        public IActionResult CreateVendor()
        {
            if (HttpContext.Session.GetString("Status") == "logged" && HttpContext.Session.GetString("role") == "CEO")
            {

                ViewData["logged"] = "true";
                this.UnitOfWork.complete();
                return View();
            }
            return Redirect("/login");
        }
        [HttpPost]
        public IActionResult CreateVendor(Vendor v)
        {
            if (HttpContext.Session.GetString("Status") == "logged" && HttpContext.Session.GetString("role") == "CEO")
            {
                this.UnitOfWork.Vendor.Add(v);
                ViewData["logged"] = "true";
                this.UnitOfWork.complete();
                return RedirectToAction("Index");
            }
            return Redirect("/login");
        }
        [HttpGet]
        public IActionResult EditVendor(int id)
        {
            if (HttpContext.Session.GetString("Status") == "logged" && HttpContext.Session.GetString("role") == "CEO")
            {

                ViewData["logged"] = "true";

                return View(this.UnitOfWork.Vendor.GetById(id));

            }
            return Redirect("/login");
        }

        [HttpPost]
        public IActionResult EditVendor(Vendor v)
        {
            if (HttpContext.Session.GetString("Status") == "logged" && HttpContext.Session.GetString("role") == "CEO")
            {
                this.UnitOfWork.Vendor.UpdateVendor(v);
                this.UnitOfWork.complete();
                return RedirectToAction("Index");

            }
            return Redirect("/login");
        }

    }
}

Entreprise/Views/Vendor/CreateVendor.cshtml
@model Entreprise.Models.Vendor

@{
    ViewData["Title"] = "CreateVendor";
}



<section class="d-flex align-items-center justify-content-center">
    <div class="container" data-aos="fade-up">
        <!-- ======= Contact Section ======= -->
        <section id="contact" class="contact">
            <div class="container" data-aos="fade-up">
<h1>CreateVendor</h1>

<h4>Vendor</h4>
<hr />



<div class="row">
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateVendor">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone_Number" class="control-label"></label>
                <input asp-for="Phone_Number" class="form-control" />
                <span asp-validation-for="Phone_Number" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

                </div>
        </section><!-- End Contact Section -->
        <!-- End About Section -->

    </div>
</section>

Entreprise/Views/Vendor/EditVendor.cshtml
@model Entreprise.Models.Vendor

@{
    ViewData["Title"] = "EditVendor";
}
<section class="d-flex align-items-center justify-content-center">
    <div class="container" data-aos="fade-up">
        <!-- ======= Contact Section ======= -->
        <section id="contact" class="contact">
            <div class="container" data-aos="fade-up">
<h1>EditVendor</h1>

<h4>Vendor</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditVendor">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone_Number" class="control-label"></label>
                <input asp-for="Phone_Number" class="form-control" />
                <span asp-validation-for="Phone_Number" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>


            </div>
        </section><!-- End Contact Section -->
        <!-- End About Section -->

    </div>
</section>

Entreprise/Views/Vendor/Index.cshtml
@{
    ViewData["Title"] = "Vendor";
}
@model List<Vendor>

<section class="d-flex align-items-center justify-content-center">

    <div class="container" data-aos="fade-up">


        <section id="team" class="team">
            <div class="container" data-aos="fade-up">

                <div class="section-title">
                    <h2 style="font-size: xx-large;color:black">Vendors</h2>
                </div>
                 
                    @if (ViewData["role"].Equals("CEO"))
                         {
                             <a>
                                @Html.ActionLink("Add Vendor", "CreateVendor", "Vendor",null,new {@class="btn btn-warning"})
                            </a> 
                        }
                <br /><br />

                <div class="row">
                    @foreach(Vendor v in Model)
                    {
                        <div class="col-lg-4 col-md-6 d-flex align-items-stretch" data-aos="zoom-in" data-aos-delay="100">
                            <div class="icon-box">
                                <div class="icon"><i class="bi bi-truck"></i></div>
                                <h4><a href="@Url.Action("VendorProducts", "Vendor",new {id = @v.Id})">@v.Name</a></h4>
                                <p>@v.Email</p>
                                <p>@v.Phone_Number</p>
                            </div>
                            <div>
                            @if (ViewData["role"].Equals("CEO"))
                            {
                                    <div class="row">
                                        <div class="col">
                                            @Html.ActionLink("Edit", "EditVendor", "Vendor",new {id = @v.Id },new {@class="btn btn-warning"})

                                        </div>
                                        <div class="col">
                                            @Html.ActionLink("Delete", "DeleteVendor", "Vendor",new {id = @v.Id},new {@class="btn btn-outline-danger"})

                                        </div>
                                   </div>
                            }
                            </div>
                        </div>
                    }

                   


                </div>
            </div>


        </section> 


    </div>
</section>

Entreprise/Views/Vendor/VendorProducts.cshtml
@{
    ViewData["Title"] = "Products";
}
@model List<Product>

<section class="d-flex align-items-center justify-content-center">
    <div class="container" data-aos="fade-up">

        <div class="section-title">
            <h2 style="font-size: xx-large;color:black">Vendor: @Model.First().Vendor.Name</h2>

            @if (ViewData["role"].Equals("CEO"))
            {
                <a>
                    @Html.ActionLink("Add Product", "CreateProduct", "Stock",null,new {@class="btn btn-warning"})
                </a>
            }
        </div>

        <div class="row">

            @foreach (Product p in @Model)
            {

                <div class="col-lg-3 col-md-6 d-flex align-items-stretch">

                    <div class="product" data-aos="fade-up" data-aos-delay="50">
                        <div class="member-img">
                            <img src="~/img/portfolio/portfolio-@(p.Id).jpg" class="img-fluid" alt="">

                        </div>


                        <div class="product-info">
                            <a href="~/img/portfolio/portfolio-@(p.Id).jpg" data-gallery="portfolioGallery" class="portfolio-lightbox" title="@p.Name"><i class="bx bx-plus"></i></a>
                            <a href="@Url.Action("Details", "Stock",new {id = @p.Id})">
                                <h4>@p.Name</h4>
                            </a>
                        </div>

                    </div>
                </div>
            }

        </div>


    </div>
</section>