Entreprise/Controllers/TeamsController.cs
using Entreprise.Data;
using Entreprise.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Formatters;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Diagnostics;

namespace Entreprise.Controllers
{

    public class TeamsController : Controller
    {

        private Unit UnitOfWork;
        public TeamsController()
        {
            this.UnitOfWork = new Unit();
        }
        public IActionResult Index()
        {
            if (HttpContext.Session.GetString("Status") == "logged")
            {
                ViewData["role"] = this.UnitOfWork.User.getByID(Convert.ToInt32(HttpContext.Session.GetString("pid"))).ROLE;

                ViewData["logged"] = "true";
                return View((ICollection<Department>)this.UnitOfWork.Department.GetLIST());

            }
            return Redirect("/login");

        }
        public IActionResult Team(string id)
        {
            if (HttpContext.Session.GetString("Status") == "logged")
            {

                ViewData["role"] = this.UnitOfWork.User.getByID(Convert.ToInt32(HttpContext.Session.GetString("pid"))).ROLE;

                ViewData["logged"] = "true";
                ViewData["Dep"] = id;
                return View((List<User>)this.UnitOfWork.User.Find(x => x.Department.Name == id));

            }
            return Redirect("/login");

        }
        public IActionResult AllTeam(string id)
        {
            if (HttpContext.Session.GetString("Status") == "logged")
            {

                ViewData["role"] = this.UnitOfWork.User.getByID(Convert.ToInt32(HttpContext.Session.GetString("pid"))).ROLE;
                ViewData["logged"] = "true";
                return View((List<User>)this.UnitOfWork.User.GetAll());

            }
            return Redirect("/login");

        }
        public IActionResult Member(int id)
        {
            if (HttpContext.Session.GetString("Status") == "logged")
            {

                ViewData["role"] = this.UnitOfWork.User.getByID(Convert.ToInt32(HttpContext.Session.GetString("pid"))).ROLE;
                ViewData["logged"] = "true";
                return View((User)this.UnitOfWork.User.GetById(id));

            }
            return Redirect("/login");

        }

        public IActionResult Delete(int id)
        {
            if (HttpContext.Session.GetString("Status") == "logged" && HttpContext.Session.GetString("role") == "CEO")
            {
                this.UnitOfWork.User.Remove((User)this.UnitOfWork.User.GetById(id));

                ViewData["logged"] = "true";
                this.UnitOfWork.complete();
                return RedirectToAction("AllTeam");
            }
            return Redirect("/login");
        }
        

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var user= this.UnitOfWork.User.getByID(id);
            if(user == null)
            {
                return RedirectToAction("AllTeam");

            }
            return View(user);
        }
        [HttpPost]
        public IActionResult Edit(User u)
        {
            if (HttpContext.Session.GetString("Status") == "logged")
            {
                this.UnitOfWork.User.updateUser(u.Id,u);
                return RedirectToAction("AllTeam");
            }

            return Redirect("/login");
        }


        [HttpGet]
        public IActionResult AddMember()
        {
            if (HttpContext.Session.GetString("Status") == "logged" && HttpContext.Session.GetString("role") == "CEO")
            {
                MyViewModel model = new MyViewModel();
                model.user = new User();

                model.did = 0;
                ViewData["role"] = this.UnitOfWork.User.getByID(Convert.ToInt32(HttpContext.Session.GetString("pid"))).ROLE;
                ViewData["logged"] = "true";
                return View();

            }
            return Redirect("/login");

        }
        [HttpPost]
        public IActionResult AddMember(MyViewModel model)
        {
            if (HttpContext.Session.GetString("Status") == "logged")
            {

                User user = new User();
                user.Id = model.user.Id;
                user.Firstname = model.user.Firstname;
                user.Lastname = model.user.Lastname;

                user.Email = model.user.Password;
                user.Password = model.user.Password;

                user.Phone_Number = model.user.Phone_Number;
                user.Function = model.user.Function ;
                user.ROLE = model.user.ROLE;
                user.Department = (Department) this.UnitOfWork.Department.GetById( model.did);
                this.UnitOfWork.User.Add(user);
                this.UnitOfWork.complete();
                return RedirectToAction("AllTeam");

            }
            return Redirect("/login");

        }
    }
}

Entreprise/Controllers/VendorController.cs
using Entreprise.Data;
using Entreprise.Models;
using Microsoft.AspNetCore.Mvc;

namespace Entreprise.Controllers
{
    public class VendorController : Controller
    {
        private Unit UnitOfWork;
        public VendorController()
        {
            this.UnitOfWork = new Unit();
        }
        public IActionResult Index()
        {
            if (HttpContext.Session.GetString("Status") == "logged")
            {
                ViewData["role"] = this.UnitOfWork.User.getByID(Convert.ToInt32(HttpContext.Session.GetString("pid"))).ROLE;
                ViewData["logged"] = "true";
                return View(this.UnitOfWork.Vendor.GetAll());

            }
            return Redirect("/login");
        }
        public IActionResult VendorProducts(int id)
        {
            if (HttpContext.Session.GetString("Status") == "logged")
            {
                ViewData["role"] = this.UnitOfWork.User.getByID(Convert.ToInt32(HttpContext.Session.GetString("pid"))).ROLE;
                ViewData["logged"] = "true";
                return View(this.UnitOfWork.Product.GetbyVendor(this.UnitOfWork.Vendor.GetById(id)));
                //return View(this.UnitOfWork.Vendor.GetById(id).Products);
            }
            return Redirect("/login");
        }

        public IActionResult DeleteVendor(int id)
        {
            if (HttpContext.Session.GetString("Status") == "logged" && HttpContext.Session.GetString("role") == "CEO")
            {

                this.UnitOfWork.Vendor.Remove((Vendor)this.UnitOfWork.Vendor.GetById(id));
                ViewData["logged"] = "true";
                this.UnitOfWork.complete();
                return RedirectToAction("Index");
            }
            return Redirect("/login");

        }
        [HttpGet]
        public IActionResult CreateVendor()
        {
            if (HttpContext.Session.GetString("Status") == "logged" && HttpContext.Session.GetString("role") == "CEO")
            {

                ViewData["logged"] = "true";
                this.UnitOfWork.complete();
                return View();
            }
            return Redirect("/login");
        }
        [HttpPost]
        public IActionResult CreateVendor(Vendor v)
        {
            if (HttpContext.Session.GetString("Status") == "logged" && HttpContext.Session.GetString("role") == "CEO")
            {
                this.UnitOfWork.Vendor.Add(v);
                ViewData["logged"] = "true";
                this.UnitOfWork.complete();
                return RedirectToAction("Index");
            }
            return Redirect("/login");
        }
        [HttpGet]
        public IActionResult EditVendor(int id)
        {
            if (HttpContext.Session.GetString("Status") == "logged" && HttpContext.Session.GetString("role") == "CEO")
            {

                ViewData["logged"] = "true";

                return View(this.UnitOfWork.Vendor.GetById(id));

            }
            return Redirect("/login");
        }

        [HttpPost]
        public IActionResult EditVendor(Vendor v)
        {
            if (HttpContext.Session.GetString("Status") == "logged" && HttpContext.Session.GetString("role") == "CEO")
            {
                this.UnitOfWork.Vendor.UpdateVendor(v);
                this.UnitOfWork.complete();
                return RedirectToAction("Index");

            }
            return Redirect("/login");
        }

    }
}

Entreprise/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>@ViewData["Title"] </title>
    <meta content="" name="description">
    <meta content="" name="keywords">
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
          rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="~/vendor/aos/aos.css" rel="stylesheet">
    <link href="~/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="~/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="~/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
    <link href="~/vendor/remixicon/remixicon.css" rel="stylesheet">
    <link href="~/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="~/css/style.css" rel="stylesheet">

</head>

<body>
 
    <header id="header" style="background: black;opacity: 0.8" class="fixed-top ">
        <div class="container d-flex align-items-center justify-content-lg-between">

            <h1 class="logo me-auto me-lg-0"><a href="index.html">Entreprise<span>.</span></a></h1>
    
            @if ((string?)ViewData["Title"] != "Login" && (string?)ViewData["Title"] != "Home")
            {
            <nav id="navbar" class="navbar order-last order-lg-0">
                <ul>
                    <li> @Html.ActionLink("Home", "Index", "Home")</li>
                        <li class="nav-link scrollto"> @Html.ActionLink("Tasks", "Index", "Tasks")</li>
                        <li class="nav-link scrollto">@Html.ActionLink("Team", "Index", "Teams")</li>
                        <li class="nav-link scrollto">@Html.ActionLink("Stock", "Index", "Stock")</li>
                        <li class="nav-link scrollto"> @Html.ActionLink("Vendors", "Index", "Vendor")</li>
                        <li class="nav-link scrollto"> @Html.ActionLink("Profile", "Profile", "Login")</li>
                </ul>
                <i class="bi bi-list mobile-nav-toggle"></i>
            </nav>
}
            @if (ViewData["logged"]=="true"){
                <div class="get-started-btn scrollto">@Html.ActionLink("Log Out", "Logout", "Login")</div>
            }
        </div>
    </header>
  
    @RenderBody()


    <div id="preloader"></div>
    <a href="#" class="back-to-top d-flex align-items-center justify-content-center">
        <i class="bi bi-arrow-up-short"></i>
    </a>

    <!-- Vendor JS Files -->
    <script src="~/vendor/purecounter/purecounter_vanilla.js"></script>
    <script src="~/vendor/aos/aos.js"></script>
    <script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/vendor/glightbox/js/glightbox.min.js"></script>
    <script src="~/vendor/isotope-layout/isotope.pkgd.min.js"></script>
    <script src="~/vendor/swiper/swiper-bundle.min.js"></script>
    <script src="~/vendor/php-email-form/validate.js"></script>

    <!-- Template Main JS File -->
    <script src="~/js/main.js"></script>
    @await RenderSectionAsync("Styles", required: false)
</body>

</html>